import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

test.describe('Agent Skill Registry - E2E Core Audit Suite', () => {

  test.beforeEach(async ({ page }) => {
    // Navigate to the dashboard before each test
    await page.goto(BASE_URL);
  });

  test('1. Dashboard, Brand & Route Navigation Check', async ({ page }) => {
    // Verify Page Title
    await expect(page).toHaveTitle(/AI Skill Registry/i);

    // Verify Brand Identity
    await expect(page.locator('text=Universal AI Skill Lab')).toBeVisible();

    // Verify Desktop Sidebar Navigation Links
    const dashboardNav = page.getByTestId('nav-dashboard');
    const builderNav = page.getByTestId('nav-builder');
    const registryNav = page.getByTestId('nav-registry');
    const consoleNav = page.getByTestId('nav-console');
    const syncNav = page.getByTestId('nav-sync');
    const historyNav = page.getByTestId('nav-history');
    const governanceNav = page.getByTestId('nav-governance');

    await expect(dashboardNav).toBeVisible();
    await expect(builderNav).toBeVisible();
    await expect(registryNav).toBeVisible();
    await expect(consoleNav).toBeVisible();
    await expect(syncNav).toBeVisible();
    await expect(historyNav).toBeVisible();
    await expect(governanceNav).toBeVisible();

    // Verify Quick Actions Menu is interactive (Desktop header/Mobile header visible check)
    const quickActionsBtn = page.locator('[data-testid="quick-actions-menu"]:visible');
    await expect(quickActionsBtn).toBeVisible();
    await quickActionsBtn.click();
    
    // Use first() to avoid strict mode violations if same text is rendered elsewhere
    await expect(page.locator('text=Run Diagnostics').first()).toBeVisible();
    await expect(page.locator('text=Sync All').first()).toBeVisible();

    // Test Dashboard "Open Skill Builder" CTA Button (fixed button design)
    const openBuilderBtn = page.getByTestId('dashboard-open-builder');
    await expect(openBuilderBtn).toBeVisible();
    await openBuilderBtn.click();
    await expect(page).toHaveURL(/.*\/builder/);
  });

  test('2. Skill Builder Multi-Step Wizard Flow', async ({ page }) => {
    await page.goto(`${BASE_URL}/builder`);

    // Verify we are on Step 1: Purpose
    await expect(page.locator('h2:has-text("Purpose")')).toBeVisible();
    
    // Fill out Step 1
    const nameInput = page.getByTestId('builder-name');
    await nameInput.fill('e2e-playwright-skill');
    
    const descInput = page.getByTestId('builder-description');
    await descInput.fill('An automated E2E testing package generated by Playwright.');

    const triggerInput = page.getByTestId('builder-triggers');
    await triggerInput.fill('trigger e2e tests');
    await triggerInput.press('Enter');

    // Go to Step 2: Metadata
    await page.getByTestId('builder-next').click();
    await expect(page.locator('h2:has-text("Metadata")')).toBeVisible();

    // Select Metadata options
    await page.getByTestId('builder-tier').selectOption('atomic');
    await page.getByTestId('builder-status').selectOption('draft');
    await page.getByTestId('builder-trust-T1').click();

    // Go to Step 3: Tools & Runtime
    await page.getByTestId('builder-next').click();
    await expect(page.locator('h2:has-text("Tools & Runtime")')).toBeVisible();
    
    await page.getByTestId('builder-role').selectOption('researcher');
    // Toggle filesystem MCP server config
    const mcpChip = page.getByTestId('chip-filesystem');
    await expect(mcpChip).toBeVisible();

    // Go to Step 4: Instructions
    await page.getByTestId('builder-next').click();
    await expect(page.locator('h2:has-text("Instructions")')).toBeVisible();

    const instructionsTextarea = page.getByTestId('builder-instructions');
    await instructionsTextarea.fill('## Core Directive\nExecute Playwright tests on command.\n\n## Verification\nEnsure tests pass without error.');

    // Go to Step 5: Governance
    await page.getByTestId('builder-next').click();
    await expect(page.locator('h2:has-text("Governance")')).toBeVisible();

    // Run Deduplication and Governance Checks
    const dedupeBtn = page.getByTestId('builder-dedupe-btn');
    await dedupeBtn.click();
    await expect(page.locator('text=Deduplication')).toBeVisible();

    const govBtn = page.getByTestId('builder-governance-btn');
    await govBtn.click();

    // Go to Step 6: Preview
    await page.getByTestId('builder-next').click();
    await expect(page.locator('h2:has-text("Preview")')).toBeVisible();
    // Use first() to avoid strict-mode violation (live preview vs. main card)
    await expect(page.locator('pre:has-text("name: e2e-playwright-skill")').first()).toBeVisible();

    // Go to Step 7: Validate & Save
    await page.getByTestId('builder-next').click();
    await expect(page.locator('h2:has-text("Validate & Save")')).toBeVisible();

    const validateBtn = page.getByTestId('builder-validate-btn');
    await validateBtn.click();
    await expect(page.locator('text=overall').first()).toBeVisible();

    const saveDraftBtn = page.getByTestId('builder-savedraft-btn');
    await expect(saveDraftBtn).toBeVisible();
  });

  test('3. Simulated Operations Console & Presets', async ({ page }) => {
    await page.goto(`${BASE_URL}/console`);

    // Verify Console Inputs
    const consoleInput = page.getByTestId('console-input');
    await expect(consoleInput).toBeVisible();
    await consoleInput.fill('aiskill list');

    // Run custom command
    await page.getByTestId('console-run').click();

    // Verify simulation output contains "list" in the output container
    await expect(page.locator('.gp-inset')).toContainText('list', { timeout: 15000 });

    // Execute preset command
    const doctorPreset = page.getByTestId('preset-aiskill doctor');
    await expect(doctorPreset).toBeVisible();
    await doctorPreset.click();

    // Check terminal output updates for doctor command execution
    await expect(page.locator('.gp-inset')).toContainText('doctor', { timeout: 15000 });

    // Tab Navigation within Console
    await page.locator('button:has-text("Logs")').click();
    await expect(page.locator('text=Logging is managed by Vercel')).toBeVisible();

    await page.locator('button:has-text("Recent Output")').click();
    await expect(page.locator('text=exit 0').first()).toBeVisible();

    await page.locator('button:has-text("Presets")').click();
    await expect(page.locator('text=explain dashboard').first()).toBeVisible();
  });

  test('4. Security Governance Gate Auditing', async ({ page }) => {
    await page.goto(`${BASE_URL}/governance`);

    // Testing a high-risk / dangerous command
    const gateInput = page.getByTestId('gate-input');
    await gateInput.fill('sudo rm -rf /');
    await page.getByTestId('gate-run').click();

    // Check for exact BLOCKED status badge (using text-is to avoid matching headers)
    await expect(page.locator('span:text-is("BLOCKED")')).toBeVisible({ timeout: 15000 });

    // Testing a safe command
    await gateInput.fill('ls -la');
    await page.getByTestId('gate-run').click();

    // Check for exact PASS status badge
    await expect(page.locator('span:text-is("PASS")')).toBeVisible({ timeout: 15000 });

    // Verify policies and rules lists are visible
    await expect(page.locator('text=Execution Policy')).toBeVisible();
    await expect(page.locator('text=Trust Tier Rules')).toBeVisible();
    await expect(page.locator('text=Blocked Command Patterns')).toBeVisible();
  });

  test('5. Skill Registry Filters, Search & Database Details', async ({ page }) => {
    await page.goto(`${BASE_URL}/skills`);

    // Verify Search Bar is loaded
    const searchBar = page.getByTestId('registry-search');
    await expect(searchBar).toBeVisible();

    // Test search filter
    await searchBar.fill('router');
    // Ensure only matching cards are shown using heading-level locator to avoid path collisions
    await expect(page.locator('h3:text-is("provider-router")')).toBeVisible();
    await expect(page.locator('h3:text-is("eval-harness-architect")')).not.toBeVisible();

    // Reset search
    await searchBar.fill('');

    // Test select filters
    const tierSelect = page.getByTestId('filter-tier');
    await tierSelect.selectOption('planning');
    await expect(page.locator('h3:text-is("skillx-planner")')).toBeVisible();
    await expect(page.locator('h3:text-is("mcp-router")')).not.toBeVisible();

    // Revert filters to all
    await tierSelect.selectOption('all');

    // Click skill card to open detailed description (DB integration verification)
    const card = page.getByTestId('skill-card-system-audit');
    await expect(card).toBeVisible();
    await card.click();

    // Detailed description pane should display on right (Desktop) or drawer (Mobile)
    await expect(page.locator('text=Runs a safe read-only audit').first()).toBeVisible();
    await expect(page.locator('text=Open full page →').first()).toBeVisible();
  });

  test('6. Run History Records & Database Interactions', async ({ page }) => {
    await page.goto(`${BASE_URL}/history`);

    // Verify Run History page is loaded
    await expect(page.locator('text=Every simulated execution')).toBeVisible();

    // If any history records are loaded, verify details expand
    const historyRowsCount = await page.locator('[data-testid^="history-row-"]').count();
    if (historyRowsCount > 0) {
      const firstRow = page.locator('[data-testid^="history-row-"]').first();
      await firstRow.click();
      
      // Details drawer should expand and show rerun and delete buttons
      await expect(page.locator('button:has-text("Copy output")').first()).toBeVisible();
      await expect(page.locator('button:has-text("Re-run")').first()).toBeVisible();
    }
  });

  test('7. UI/UX Design Hierarchy & Access Audit', async ({ page }) => {
    // Accessibility check: Ensure semantic H1 is used on pages
    await page.goto(BASE_URL);
    const h1 = page.locator('h1');
    await expect(h1).toBeVisible();
    expect(await h1.count()).toBe(1);

    // Verify styling tokens: Check background has dark mode ink background applied
    const body = page.locator('body');
    await expect(body).toHaveCSS('background-color', 'rgb(10, 10, 10)'); // corresponds to #0a0a0a
  });

  test('8. Librarian Panel AI Knowledge & Context Query', async ({ page }) => {
    await page.goto(BASE_URL);

    // Summon Librarian Panel
    const summonLibrarian = page.getByTestId('summon-librarian');
    await expect(summonLibrarian).toBeVisible();
    await summonLibrarian.click();

    // Verify Panel Header / Brand identity is visible
    await expect(page.locator('text=Docs & Institutional Knowledge')).toBeVisible();

    // Type query in the Librarian chat input
    const librarianInput = page.getByPlaceholder('Ask anything about the lab…');
    await expect(librarianInput).toBeVisible();
    await librarianInput.fill('how do I run doctor');

    // Click Send
    await page.locator('button:has-text("Send")').click();

    // Wait for the response to load (we check for console block code for aiskill doctor)
    const commandBlock = page.locator('code:has-text("aiskill doctor")').first();
    await expect(commandBlock).toBeVisible({ timeout: 15000 });

    // Close the panel using Escape key
    await page.keyboard.press('Escape');
    await expect(page.locator('text=Docs & Institutional Knowledge')).not.toBeVisible();
  });
  
  test('9. Split-Screen Skill Playground Sandbox & Editing', async ({ page }) => {
    await page.goto(`${BASE_URL}/skills/system-audit`);

    // Verify split screen components are visible
    const rawEditor = page.getByTestId('skill-raw-editor');
    await expect(rawEditor).toBeVisible();

    const sandboxInput = page.getByTestId('sandbox-input');
    await expect(sandboxInput).toBeVisible();

    // Verify required MCP status elements exist
    await expect(page.locator('text=Target MCP Configuration')).toBeVisible();

    // Type a prompt in sandbox input and run
    await sandboxInput.fill('Run a sample audit log test');
    await page.getByTestId('sandbox-submit').click();

    // Verify chat timeline updates and response appears
    const chatTimeline = page.getByTestId('sandbox-chat-timeline');
    await expect(chatTimeline).toContainText('Run a sample audit log test');

    // Wait for the LLM response to load. Real API response might take 5-10s
    await expect(page.locator('text=TRACE: Planning & Tool Execution').first()).toBeVisible({ timeout: 15000 });

    // Verify raw editor editing and save
    const editorContent = await rawEditor.inputValue();
    expect(editorContent).toContain('system-audit');

    // Make an edit (e.g. append a comment line)
    await rawEditor.fill(editorContent + '\n# e2e test edit comment');
    const saveBtn = page.getByTestId('detail-save-resync');
    await expect(saveBtn).toBeVisible();
    await saveBtn.click();

    // Verify button goes through saving state and returns success toast or completes
    await expect(page.locator('text=Skill saved & registry synced successfully!').first()).toBeVisible();
  });
});
