/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as CliRouteImport } from './routes/cli'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as OrchestratorRouteImport } from './routes/orchestrator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsSkillIdRouteImport } from './routes/skills/$skillId'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorRoute = OrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/orchestrator': typeof OrchestratorRoute
  '/cli': typeof CliRoute
  '/console': typeof ConsoleRoute
  '/evals': typeof EvalsRoute
  '/governance': typeof GovernanceRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/logs': typeof LogsRoute
  '/mcp': typeof McpRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/orchestrator': typeof OrchestratorRoute
  '/cli': typeof CliRoute
  '/console': typeof ConsoleRoute
  '/evals': typeof EvalsRoute
  '/governance': typeof GovernanceRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/logs': typeof LogsRoute
  '/mcp': typeof McpRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/orchestrator': typeof OrchestratorRoute
  '/cli': typeof CliRoute
  '/console': typeof ConsoleRoute
  '/evals': typeof EvalsRoute
  '/governance': typeof GovernanceRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/logs': typeof LogsRoute
  '/mcp': typeof McpRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/orchestrator'
    | '/cli'
    | '/console'
    | '/evals'
    | '/governance'
    | '/history'
    | '/integrations'
    | '/logs'
    | '/mcp'
    | '/providers'
    | '/settings'
    | '/sync'
    | '/skills/$skillId'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/orchestrator'
    | '/cli'
    | '/console'
    | '/evals'
    | '/governance'
    | '/history'
    | '/integrations'
    | '/logs'
    | '/mcp'
    | '/providers'
    | '/settings'
    | '/sync'
    | '/skills/$skillId'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/orchestrator'
    | '/cli'
    | '/console'
    | '/evals'
    | '/governance'
    | '/history'
    | '/integrations'
    | '/logs'
    | '/mcp'
    | '/providers'
    | '/settings'
    | '/sync'
    | '/skills/$skillId'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  OrchestratorRoute: typeof OrchestratorRoute
  CliRoute: typeof CliRoute
  ConsoleRoute: typeof ConsoleRoute
  EvalsRoute: typeof EvalsRoute
  GovernanceRoute: typeof GovernanceRoute
  HistoryRoute: typeof HistoryRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LogsRoute: typeof LogsRoute
  McpRoute: typeof McpRoute
  ProvidersRoute: typeof ProvidersRoute
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrator': {
      id: '/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof OrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  OrchestratorRoute: OrchestratorRoute,
  CliRoute: CliRoute,
  ConsoleRoute: ConsoleRoute,
  EvalsRoute: EvalsRoute,
  GovernanceRoute: GovernanceRoute,
  HistoryRoute: HistoryRoute,
  IntegrationsRoute: IntegrationsRoute,
  LogsRoute: LogsRoute,
  McpRoute: McpRoute,
  ProvidersRoute: ProvidersRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
